/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef SFX_H_
# define SFX_H_

const char *sfx_frag =
 "#version 130\n"
 "#define PI radians(180.)\n"
 "float f(float i)"
 "{"
   "return clamp(i,-1.,1.);"
 "}"
 "float i(float f)"
 "{"
   "return smoothstep(0.,.01,f);"
 "}"
 "float p(float i)"
 "{"
   "return sin(2.*PI*mod(i,1.));"
 "}"
 "float t(float i)"
 "{"
   "return sign(2.*fract(i)-1.);"
 "}"
 "float f(float i,float P)"
 "{"
   "return sign(2.*fract(i)-1.+P);"
 "}"
 "float r(float i)"
 "{"
   "return f(50.*p(i));"
 "}"
 "float i(float i,float P)"
 "{"
   "return f(50.*(p(i)-P));"
 "}"
 "float s(float i)"
 "{"
   "return 4.*abs(fract(i)-.5)-1.;"
 "}"
 "float N(float i)"
 "{"
   "return 2.*fract(i)-1.;"
 "}"
 "float w(float f)"
 "{"
   "return 32.7*pow(2.,f/12.);"
 "}"
 "float g(int i)"
 "{"
   "return 1.-2.*float(i%2);"
 "}"
 "float d(int i)"
 "{"
   "return round(sin(.5*PI*float(i)));"
 "}"
 "float n(float i)"
 "{"
   "return fract(sin(dot(vec2(i),vec2(12.9898,78.233)))*43758.5);"
 "}\n"
 "#define pat4(a,b,c,d,x)mod(x,1.)<.25?a:mod(x,1.)<.5?b:mod(x,1.)<.75?c:d\n"
 "const float m=35.,l=m/60.,e=60./m,x=44100.,a=1./x,K=.001;"
 "float N(float f,float i,float P,float K)"
 "{"
   "return smoothstep(-1e-05,i,f)-(1.-K)*smoothstep(0.,P,f-i);"
 "}"
 "float N(float i,float f,float K,float P,float N,float s,float l)"
 "{"
   "float r=i/K,a=1.-(1.-s)*(i-P-K)/N,x=i<=f-l?1.:(f-i)/l;"
   "return i<K?r:i<K+P?1:i<K+P+N?a:i<=f-l?s:i<=f?(f-i)/l:0.;"
 "}"
 "float v(float i)"
 "{"
   "return 2./PI*atan(i);"
 "}"
 "float N(float i,float P)"
 "{"
   "return abs(i)<P?i:floor(4.*i+.5)*.25;"
 "}"
 "float d(float f,float i,float P,float s,float K,float N,float l)"
 "{"
   "float r,a=sign(f);"
   "f=abs(f);"
   "if(f<P)"
     "r=s*smoothstep(0.,P,f);"
   "else"
     " if(f<K)"
       "r=K+(s-K)*smoothstep(K,P,f);"
     "else"
       " if(f<=N)"
         "r=f;"
       "else"
         " if(f<=1.)"
           "{"
             "float p=(f-N)/(1.-N);"
             "r=N+(l-N)*(1.5*p*(1.-.33*p*p));"
           "}"
         "else"
           " return 1.;"
   "return a*mix(f,r,i);"
 "}"
 "float d(int i,float P)"
 "{"
   "return P*g(i);"
 "}"
 "float g(int i,float p)"
 "{"
   "return i%2==0?0.:p*p*d(i);"
 "}"
 "float N(int i,float P,float f)"
 "{"
   "return i%2==0?0.:P*(1.-d(i))*p(f);"
 "}"
 "float d(int i,float P,float f)"
 "{"
   "return i%2==0?0.:P*(g(i)*p(f*float(i)+.25)-1.);"
 "}"
 "float N(float i,float f,float P,int s,int K,float l,float r,float x,float a,float m,float e,float T,int D)"
 "{"
   "float b=0.,n=D==1?1./r:f/r,c=D==1?1./m:1./(m*f),I=f*i+P;"
   "for(int u=1;u<=s;u+=K)"
     "{"
       "float y=float(u),h=1./y,o=l<0.?(l+1.)*g(u,h)+-l*d(u,h):l<1.?l*g(u,h)+(1.-l)*N(u,h,T):(l-1.)*d(u,h,T)+(2.-l)*N(u,h,T),q=pow(1.+pow(y*n,x),-.5)+a*exp(-pow((y*f-r)*c,2.));"
       "if(abs(q*o)<1e-06)"
         "break;"
       "b+=o*q*(p(y*I)+p(y*I*(1.+e)));"
     "}"
   "return v(b);"
 "}"
 "float n(float i,float f)"
 "{"
   "if(f>0.)"
     "return abs(f)*.8*p(i+.35*p(i));"
   "else"
     " return abs(f)*p(i+.5*PI);"
 "}"
 "float N(float i,float P,float f,float s,float r,float m,float N,float a,float K,float y,float e,float h,float x,float T,float l,float u)"
 "{"
   "int b=int(u);"
   "float D=a*P*i+f,c=K*P*i+f,q=y*P*i+f,d=e*P*i+f,I=0.,o=0.,g=0.,S=0.,W=0.,t=0.;"
   "if(b==1)"
     "g=1.,S=1.,t=1.;"
   "else"
     " if(b==2)"
       "o=1.,S=1.,t=1.;"
     "else"
       " if(b==3)"
         "I=1.,S=1.,t=1.;"
       "else"
         " if(b==4)"
           "o=1.,g=1.,W=1.,t=1.;"
         "else"
           " if(b==5)"
             "I=1.,W=1.,t=1.;"
           "else"
             " if(b==6)"
               "g=1.,S=1.;"
             "else"
               " if(b==7)"
                 "g=1.,S=1.,W=1.;"
               "else"
                 " if(b==8)"
                   "t=1.,g=1.;"
                 "else"
                   " if(b==9)"
                     "g=1.,o=1.,I=1.;"
                   "else"
                     " if(b==10)"
                       "g=1.,o=1.;"
                     "else"
                       " if(b==11)"
                         "g=1.;"
   "float k=N*p(d+n(d,l)),w=m*p(q+n(q,T)+g*k),O=r*p(c+n(c,x)+o*k+S*w),M=s*p(D+n(D,h)+I*k+W*w+S*O),R=M;"
   "if(t>0.)"
     "R+=O;"
   "if(W+S>0.)"
     "R+=w;"
   "if(I+o+g>0.)"
     "R+=k;"
   "return v(R);"
 "}"
 "float N(float f,float P,float s,float l,float b,float x,float a,float T)"
 "{"
   "int g=int(log(K)/log(l));"
   "float p[4]=float[4](b,x,a,T),N=0.;"
   "for(int u=0;u<8;u++)"
     "{"
       "float m=1.;"
       "for(int D=0;D<g;D++)"
         "{"
           "float I=f-float(D)*p[u]*(.8+.4*n(N));"
           "N+=m*(i(I*e)*exp(-8.*I*e)*((.5+.5*r(8.*I*e))*(2.*fract(P*I)-1.)));"
           "m*=-l;"
         "}"
     "}"
   "return.25*N;"
 "}"
 "float N(float i,float f,float P,float x,float a,float s,float r,float T,float p,float m)"
 "{"
   "float b=i,g=-p*N(b,f,P,x,a,s,r,T),l=1.-p*p;"
   "int k=1+int((log(K)-log(l))/log(p));"
   "for(int e=0;e<k;e++)"
     "b-=m*(.9+.2*n(i)),g+=l*N(b,f,P,x,a,s,r,T),l*=p*(1.+.01*n(b));"
   "return g;"
 "}"
 "float N(float i,float f,float P,float x,float a,float s,float r,float T,float p,float h,float m)"
 "{"
   "float b=i,g=-p*N(b,f,P,x,a,s,r,T,p,h),l=1.-p*p;"
   "int k=1+int((log(K)-log(l))/log(p));"
   "for(int e=0;e<k;e++)"
     "b-=m*(.9+.2*n(i)),g+=l*N(b,f,P,x,a,s,r,T,p,h),l*=p*(1.+.01*n(b));"
   "return g;"
 "}"
 "float d(float i,float P,float f,float l)"
 "{"
   "int b=int(l);"
   "float s=i,g=0.;"
   "for(int K=0;K<b;K++)"
     "s=i-float(K)*a,g+=v(smoothstep(0.,.01,s)*smoothstep(.4,.1,s)*N(s,60.+90.*smoothstep(-.2,0.,-s),5.,10,1,.8,1.,1.,1.,.1,0.,0.,1)+.75*step(s,.05)*p(s*1100.*5.*N(s*800.*5.))+1.5*(1.-exp(-1000.*s))*exp(-40.*s)*p((400.-200.*s)*s*p((60.+90.*smoothstep(-.2,0.,-s))*s)))/l;"
   "return g;"
 "}"
 "float f(float i,float f,float P,float l)"
 "{"
   "int b=int(l);"
   "float s=i,g=0.;"
   "for(int K=0;K<b;K++)"
     "s=i-float(K)*a,g+=d(s,f,P,2.)/l;"
   "return g;"
 "}"
 "float d(float i,float P,float r,float l,float b,float x,float a,float T)"
 "{"
   "int g=int(log(K)/log(l));"
   "float p[4]=float[4](b,x,a,T),e=0.;"
   "for(int u=0;u<8;u++)"
     "{"
       "float m=1.;"
       "for(int D=0;D<g;D++)"
         "{"
           "float I=i-float(D)*p[u]*(.8+.4*n(e));"
           "e+=m*f(2.6*(s(I*(350.+5200.*smoothstep(-.01,0.,-I)+450.*smoothstep(-.02,-.01,-I)))*smoothstep(-.1,-.02,-I)+.7*fract(sin(I*90.)*45000.)*N(I,.05,.3,.3),-1.,1.)*N(I,0.,.25,.3));"
           "m*=-l;"
         "}"
     "}"
   "return.25*e;"
 "}"
 "float d(float i,float f,float P,float s,float x,float a,float r,float T,float p,float l)"
 "{"
   "float b=i,g=-p*d(b,f,P,s,x,a,r,T),I=1.-p*p;"
   "int k=1+int((log(K)-log(I))/log(p));"
   "for(int e=0;e<k;e++)"
     "b-=l*(.9+.2*n(i)),g+=I*d(b,f,P,s,x,a,r,T),I*=p*(1.+.01*n(b));"
   "return g;"
 "}"
 "float d(float i,float f,float P,float s,float x,float a,float r,float T,float p,float l,float m)"
 "{"
   "float b=i,g=-p*d(b,f,P,s,x,a,r,T,p,l),I=1.-p*p;"
   "int k=1+int((log(K)-log(I))/log(p));"
   "for(int e=0;e<k;e++)"
     "b-=m*(.9+.2*n(i)),g+=I*d(b,f,P,s,x,a,r,T,p,l),I*=p*(1.+.01*n(b));"
   "return g;"
 "}"
 "float f(float P,float s,float l,float b,float K,int r,float x,float T)"
 "{"
   "float g=s-l,I=g/(b-l),a=b-l,h=e*a,u=e*(s-l),t=w(K),S=i(s-l)*(1.-smoothstep(b,b+T,s)),D=p(P*t);"
   "if(r==0)"
     ";"
   "else"
     " if(r==3)"
       "D=.8*N(u,h,.001,0.,.1,1.,.3)*(d(f(1.6*N(u,t,0.,.99949*pow(x,.09444),.88144*pow(x,.49581),.99949*pow(x,.20462),.75552*pow(x,.9444),.5,1.,1.5,1.,0.,0.,0.,.3935,8.)),.3,.2,.8,.4,.8,.8)+d(f(1.6*N(u-.002*(1.+2.*p(.15*u)),t,0.,.99949*pow(x,.09444),.88144*pow(x,.49581),.99949*pow(x,.20462),.75552*pow(x,.9444),.5,1.,1.5,1.,0.,0.,0.,.3935,8.)),.3,.2,.8,.4,.8,.8)+d(f(1.6*N(u-.004*(1.+2.*p(.15*u)),t,0.,.99949*pow(x,.09444),.88144*pow(x,.49581),.99949*pow(x,.20462),.75552*pow(x,.9444),.5,1.,1.5,1.,0.,0.,0.,.3935,8.)),.3,.2,.8,.4,.8,.8));"
     "else"
       " if(r==-3)"
         "D=4.*f(u,t,h,2.);"
   "return clamp(S,0.,1.)*v(D);"
 "}"
 "uniform float iBlockOffset,iSampleRate,iVolume;"
 "uniform int iTexSize;"
 "uniform sampler2D iSequence;"
 "uniform float iSequenceWidth;"
 "float c(float i)"
 "{"
   "float f=mod(i,2.);"
   "i*=.5;"
   "vec2 P=(vec2(mod(i,iSequenceWidth),floor(i/iSequenceWidth))+.05)/iSequenceWidth;"
   "vec4 b=texture(iSequence,P);"
   "vec2 s=mix(b.xy,b.zw,f);"
   "return round(dot(vec2(255.,65280.),s));"
 "}"
 "float P(int i)"
 "{"
   "float f=c(float(i)),l=floor(f/32768.),b=floor(f/1024.-l*32.),p=f-l*32768.-b*1024.;"
   "if(b==0.)"
     "return mix(1.,-1.,l)*5.96046e-08*p;"
   "return mix(1.,-1.,l)*(1.+p*.000976563)*pow(2.,b-15.);"
 "}\n"
 "#define NTRK 2\n"
 "#define NMOD 5\n"
 "#define NPTN 2\n"
 "#define NNOT 32\n"
 "int o(int i)"
 "{"
   "return int(P(i));"
 "}"
 "int b(int i)"
 "{"
   "return int(P(i+1+1*NTRK));"
 "}"
 "float u(int i)"
 "{"
   "return P(i+1+2*NTRK);"
 "}"
 "float T(int i)"
 "{"
   "return P(i+1+3*NTRK);"
 "}"
 "float h(int i)"
 "{"
   "return P(i+1+4*NTRK);"
 "}"
 "float R(int i)"
 "{"
   "return P(i+1+4*NTRK+1*NMOD);"
 "}"
 "int O(int i)"
 "{"
   "return int(P(i+1+4*NTRK+2*NMOD));"
 "}"
 "float S(int i)"
 "{"
   "return P(i+1+4*NTRK+3*NMOD);"
 "}"
 "int D(int i)"
 "{"
   "return int(P(i+1+4*NTRK+4*NMOD));"
 "}"
 "float M(int i)"
 "{"
   "return P(i+2+4*NTRK+4*NMOD+NPTN);"
 "}"
 "float k(int i)"
 "{"
   "return P(i+2+4*NTRK+4*NMOD+NPTN+1*NNOT);"
 "}"
 "float q(int i)"
 "{"
   "return P(i+2+4*NTRK+4*NMOD+NPTN+2*NNOT);"
 "}"
 "float I(int i)"
 "{"
   "return P(i+2+4*NTRK+4*NMOD+NPTN+3*NNOT);"
 "}"
 "float W(float i)"
 "{"
   "float P=4.;"
   "int s=24;"
   "float g=10.,p=0.,K=0.,N=mod(l*i,P);"
   "if(N>P)"
     "return p;"
   "i=e*N;"
   "float r=1.,x=0.,a=0.;"
   "for(int m=0;m<NTRK;m++)"
     "{"
       "int t=o(m),W=o(m+1)-t,c=W-1;"
       "for(int w=0;w<W-1;w++)"
         "if(N<h(t+w))"
           "{"
             "c=w;"
             "break;"
           "}"
       "int w=W-1;"
       "for(int y=0;y<W-1;y++)"
         "if(N<R(t+y)+T(m))"
           "{"
             "w=y;"
             "break;"
           "}"
       "for(int y=w;y<=c;y++)"
         "{"
           "float d=N-h(t+y);"
           "int n=O(t+y),F=D(n),C=D(n+1)-F,z=C-1;"
           "for(int B=0;B<C-1;B++)"
             "if(d<M(F+B+1))"
               "{"
                 "z=B;"
                 "break;"
               "}"
           "int B=C-1;"
           "for(int V=0;V<C-1;V++)"
             "if(d<=k(F+V)+T(m))"
               "{"
                 "B=V;"
                 "break;"
               "}"
           "for(int V=B;V<=z;V++)"
             "{"
               "x=M(F+V);"
               "a=k(F+V);"
               "if(b(m)==s)"
                 "{"
                   "int Z=int(q(F+V));"
                   "if(Z==0)"
                     "r=1.-smoothstep(x,x+.0001,d)+smoothstep(x,a,d);"
                   "else"
                     " K+=u(m)*f(i,d,x,a,S(t+y),-Z,I(F+V),T(m));"
                 "}"
               "else"
                 " p+=u(m)*f(i,d,x,a,q(F+V)+S(t+y),b(m),I(F+V),T(m));"
             "}"
         "}"
     "}"
   "return v(v(r*p+K));"
 "}"
 "vec2 y(float i)"
 "{"
   "float l=.0002;"
   "return vec2(W(i),W(i-l));"
 "}"
 "void main()"
 "{"
   "float i=(iBlockOffset+gl_FragCoord.x+gl_FragCoord.y*iTexSize)/iSampleRate;"
   "vec2 p=y(i),f=floor((.5+.5*p)*65535.),b=mod(f,256.)/255.,g=floor(f/256.)/255.;"
   "gl_FragColor=vec4(b.x,g.x,b.y,g.y);"
 "}";

#endif // SFX_H_
